version: "4.0"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:${PATH_ROOT}
    ports:
      - '8000:80'
    networks:
      - app
    depends_on:
      - php

  php:
    build: ./docker
    working_dir: ${PATH_ROOT}
    restart: unless-stopped
    tty: true
    volumes:
      - .:${PATH_ROOT}
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "8006:3306"
    networks:
      - app

networks:
  app:
    driver: bridge
